# Generated by Django 5.2 on 2025-09-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietario del sistema'), ('admin', 'Administrador del sistema'), ('sysoper', 'Administrador de aplicación'), ('opera', 'Operador del sistema')], max_length=10),
        ),
    ]
