# Generated by Django 5.2 on 2025-09-08 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('detalle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_codigo', models.CharField(max_length=10, unique=True)),
                ('empresa_nombre', models.CharField(max_length=255)),
                ('empresa_telefono', models.CharField(max_length=20)),
                ('empresa_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.direccion')),
            ],
        ),
    ]
