# Generated by Django 5.2 on 2025-09-08 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina_codigo', models.CharField(max_length=10, unique=True)),
                ('oficina_nombre', models.CharField(max_length=255)),
                ('oficina_telefono', models.CharField(max_length=20)),
                ('oficina_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.direccion')),
                ('oficina_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.empresa')),
            ],
        ),
    ]
