# Generated by Django 5.2 on 2025-09-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_oficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('state_id', models.CharField(max_length=5)),
                ('state_name', models.CharField(max_length=50)),
                ('city_base', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=15)),
            ],
            options={
                'unique_together': {('country', 'state_id', 'state_name', 'city_base', 'city', 'zipcode')},
            },
        ),
    ]
