# Generated by Django 5.2 on 2025-09-10 16:40

import backend.models.direcciones
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_catalogodireccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='detalle',
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_city',
            field=models.CharField(choices=[('LAX', 'Los Angeles'), ('SFO', 'San Francisco'), ('GUA', 'Guatemala')], default='Los Angeles', max_length=20),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_codigo',
            field=models.CharField(default=backend.models.direcciones.generate_numeric_uuid, editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_country',
            field=models.CharField(choices=[('USA', 'Estado Unidos'), ('GUA', 'Guatemala')], default='Estados Unidos', max_length=20),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.empresa'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_estado_registro',
            field=models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_estado_uso',
            field=models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Principal'), (2, 'Secundaria')], default=1),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_state',
            field=models.CharField(choices=[('CA', 'California'), ('GUA', 'Guatemala')], default='CA', max_length=5),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_street_one',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_street_two',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_tipo_registro',
            field=models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Cliente'), (2, 'Usuario'), (3, 'Proveedor'), (4, 'Inmueble')], default=1),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_zipcode',
            field=models.CharField(choices=[('900', '90004'), ('010', '01011')], default='90004', max_length=20),
        ),
        migrations.AddField(
            model_name='direccion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
