# Generated by Django 5.2 on 2025-09-10 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_direccion_codigo_remove_direccion_detalle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='direccion_estado_uso',
            new_name='direccion_sts_direccion',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='direccion_estado_registro',
            new_name='direccion_sts_registro',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='direccion_tipo_registro',
            new_name='direccion_sts_tipo',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='direccion_city',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='direccion_country',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='direccion_state',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='direccion_zipcode',
        ),
        migrations.AddField(
            model_name='direccion',
            name='catalogo_direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.catalogodireccion'),
        ),
    ]
