# Generated by Django 5.2 on 2025-09-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_direccion_estado_uso_direccion_direccion_sts_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='direccion_codigo',
            field=models.CharField(default='155503701341098', editable=False, max_length=15),
        ),
    ]
