# Generated by Django 5.2 on 2025-09-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_direccion_direccion_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='direccion_codigo',
            field=models.CharField(default='155306697228626', editable=False, max_length=15),
        ),
    ]
