# Generated by Django 5.2 on 2025-09-16 22:37

import backend.models.contactos
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_direccion_direccion_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='direccion_codigo',
            field=models.CharField(default='335603682414037', editable=False, max_length=15),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto_codigo', models.CharField(default=backend.models.contactos.generate_numeric_uuid, editable=False, max_length=15)),
                ('contacto_tipo', models.IntegerField(choices=[(1, 'Cliente'), (2, 'Encargado'), (3, 'Proveedor')], default=1)),
                ('contacto_cui_tipo', models.IntegerField(choices=[(0, 'NoIdentificado'), (1, 'DPI'), (2, 'Pasaporte'), (3, 'US - ID Card'), (4, 'US - Seguro Social')], default=1)),
                ('contacto_cui_registro', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_nombres', models.CharField(max_length=100)),
                ('contacto_apellido_uno', models.CharField(max_length=30)),
                ('contacto_apellido_dos', models.CharField(max_length=30)),
                ('contacto_telefono', models.CharField(blank=True, default='', max_length=20)),
                ('contacto_correo', models.EmailField(blank=True, default='', max_length=254)),
                ('contacto_direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.direccion')),
            ],
        ),
    ]
