# Generated by Django 5.2 on 2025-09-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_direccion_direccion_codigo_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='direccion_codigo',
            field=models.CharField(default='130987205350738', editable=False, max_length=15),
        ),
    ]
