# Generated by Django 5.2 on 2025-09-16 22:43

import backend.models.direcciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_direccion_direccion_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='direccion_codigo',
            field=models.CharField(default=backend.models.direcciones.generate_numeric_uuid, editable=False, max_length=15),
        ),
    ]
