# Generated by Django 5.2 on 2025-09-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_direccion_direccion_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='contacto_tipo',
            field=models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Cliente'), (2, 'Usuario'), (3, 'Encargado'), (4, 'Proveedor'), (5, 'Inmueble')], default=1),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='direccion_sts_tipo',
            field=models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Cliente'), (2, 'Usuario'), (3, 'Encargado'), (4, 'Proveedor'), (5, 'Inmueble')], default=1),
        ),
    ]
