# Generated by Django 5.2 on 2025-09-22 18:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_contacto_contacto_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_uno', models.CharField(max_length=30)),
                ('apellido_dos', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia_num', models.CharField(max_length=10, unique=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion_contenido', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sts_pago', models.IntegerField(choices=[(0, 'No Pagado'), (1, 'Pagado')], default=None, help_text='Indica si el monto fue pagado (1), no pagado (0).', null=True)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cli_dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_destinatario', to='backend.cliente')),
                ('cli_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_remitente', to='backend.cliente')),
                ('dir_dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_destinatario', to='backend.direccion')),
                ('dir_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_remitente', to='backend.direccion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.empresa')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.oficina')),
            ],
        ),
    ]
