# Generated by Django 5.2 on 2025-09-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_cliente_guia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guia',
            name='cli_dst',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='cli_src',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='dir_dst',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='dir_src',
        ),
        migrations.AddField(
            model_name='guia',
            name='dst_apellido_dos',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='dst_apellido_uno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='dst_ciudad',
            field=models.CharField(choices=[(1, 'Los Angeles'), (2, 'Oakland'), (3, 'San Francisco'), (4, 'Guatemala')], default=1),
        ),
        migrations.AddField(
            model_name='guia',
            name='dst_direccion_dos',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='dst_direccion_uno',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='dst_estado',
            field=models.CharField(choices=[(1, 'CA'), (2, 'GT')], default=1),
        ),
        migrations.AddField(
            model_name='guia',
            name='dst_nombres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='dst_pais',
            field=models.CharField(choices=[(1, 'Estados Unidos'), (2, 'Guatemala')], default=1),
        ),
        migrations.AddField(
            model_name='guia',
            name='dst_telefono_dos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='dst_telefono_uno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='dst_zipcode',
            field=models.CharField(default=90004, max_length=20),
        ),
        migrations.AddField(
            model_name='guia',
            name='src_apellido_dos',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='src_apellido_uno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='src_ciudad',
            field=models.CharField(choices=[(1, 'Los Angeles'), (2, 'Oakland'), (3, 'San Francisco'), (4, 'Guatemala')], default=1),
        ),
        migrations.AddField(
            model_name='guia',
            name='src_direccion_dos',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='src_direccion_uno',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='src_estado',
            field=models.CharField(choices=[(1, 'CA'), (2, 'GT')], default=1),
        ),
        migrations.AddField(
            model_name='guia',
            name='src_nombres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='src_pais',
            field=models.CharField(choices=[(1, 'Estados Unidos'), (2, 'Guatemala')], default=1),
        ),
        migrations.AddField(
            model_name='guia',
            name='src_telefono_dos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='src_telefono_uno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='src_zipcode',
            field=models.CharField(default=90004, max_length=20),
        ),
        migrations.AlterField(
            model_name='guia',
            name='descripcion_contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='oficina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
