# Generated by Django 5.2 on 2025-09-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_state_remove_cliente_telefono_cliente_telefono_dos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='dst_ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='dst_estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='dst_pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='dst_zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='guia',
            name='src_ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='src_estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='src_pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='src_zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
