# Generated by Django 5.2 on 2025-09-25 23:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_guia_dst_ciudad_alter_guia_dst_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guia',
            old_name='dst_apellido_dos',
            new_name='dst_apellidos',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='dst_direccion_dos',
            new_name='dst_street_dos',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='dst_direccion_uno',
            new_name='dst_street_uno',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='fecha',
            new_name='fecha_crea',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='descripcion_contenido',
            new_name='lista_contenido',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='src_direccion_dos',
            new_name='src_street_dos',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='src_direccion_uno',
            new_name='src_street_uno',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='dst_apellido_uno',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='src_apellido_dos',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='src_apellido_uno',
        ),
        migrations.AddField(
            model_name='guia',
            name='fecha_guia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='guia',
            name='src_apellidos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
